# .streamlit/config.toml

[theme]
base = "light"

# Colori nativi Streamlit
primaryColor = "#22D3EE"            # pulsanti
backgroundColor = "#FFFFFF"         # sfondo app
secondaryBackgroundColor = "#F3F4F6" # input / card
textColor = "#1F2937"               # testo

# Colori extra usati dal tuo CSS
[theme.custom]
buttonHover = "#06B6D4"
outputBg = "#D1FAE5"
outputBorder = "#10B981"

# Avvisi (facoltativi, per box warning personalizzati)
[theme.custom.warn]
bg = "#fff3cd"
text = "#664d03"
border = "#ffda6a"
