name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/15 * * * *"   # ogni 15 minuti UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:
  keepalive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: APP1
            url: "https://mor-tem.streamlit.app/"
            branch: "main"     # ramo di deploy app1
          - name: APP2
            url: "https://ispezionelegale.streamlit.app/"
            branch: "MSIL"     # ramo di deploy app2
    steps:
      - name: Ping ${{ matrix.name }}
        run: |
          for i in 1 2 3; do
            ts=$(date +%s)
            curl -fsSL -H "User-Agent: keepalive-bot" --max-time 20 \
              "${{ matrix.url }}?_=$ts" -o /dev/null && break || sleep 8
          done

      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Empty commit on ${{ matrix.branch }}
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions[bot]"
          git pull origin "${{ matrix.branch }}" --rebase || true
          git commit --allow-empty -m "keepalive ${{ matrix.name }} $(date -u +'%F %T')"
          git push origin "${{ matrix.branch }}"
