name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  DEPLOY_BRANCH: MSIL   # <-- ramo usato da Streamlit

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        run: |
          ts=$(date +%s)
          curl -fsSL --max-time 20 \
            -H "User-Agent: keepalive-bot" \
            "https://ispezionelegale.streamlit.app/?_=${ts}" -o /dev/null || true

      - uses: actions/checkout@v4
        with:
          ref: ${{ env.DEPLOY_BRANCH }}

      - name: Empty commit on deploy branch
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions[bot]"
          git commit --allow-empty -m "keepalive $(date -u +'%F %T')"
          git push origin "$DEPLOY_BRANCH"
          
