name: Keep Streamlit Awake

on:
  workflow_dispatch:          # avvio manuale dal tab Actions
  schedule:
    - cron: '0 */3 * * *'     # ogni 3 ore (UTC)

permissions:
  contents: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        run: |
          curl -sS -L --max-time 20 "https://mor-tem.streamlit.app/" -o /dev/null

  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Empty commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git commit --allow-empty -m "keepalive"
          git push
